# Use a specific version of the base image
FROM python:3.8-alpine

# Install wget for the HEALTHCHECK instruction
RUN apk --no-cache add wget

RUN adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP microblog.py

RUN chmod +x boot.sh
RUN chown -R microblog:microblog ./

USER microblog

# Expose the port the app runs on
EXPOSE 5000

# Add a HEALTHCHECK instruction
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:5000/ || exit 1

ENTRYPOINT ["./boot.sh"]
