FROM python:3.8

WORKDIR /microblog

COPY requirements requirements
COPY migrations migrations
COPY requirements.txt microblog.py Makefile .pylintrc pytest.ini ./

RUN pip install -r requirements/test.txt

CMD ["make", "test"]