clients:
  - url: 'http://{{ groups["monitoring"][0] }}:3100/loki/api/v1/push'

positions:
  filename: /var/lib/promtail/positions.yaml

scrape_configs:
  - job_name: nginx-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log

  - job_name: nginx-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /var/log/nginx/error.log