global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["database.kristinadev.me:9090"]
        labels:
          instance: node-exporter
  - job_name: "flask"
    static_configs:
      - targets:
          - "{{ groups['appserver'][0] }}:8000"
          - "{{ groups['appserver'][1] }}:8000"
      labels:
        instance: flask-exporter
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
        labels:
          instance: prometheus
  - job_name: nginx
    metrics_path: /prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["{{ groups['loadbalancer'][0] }}:9113"]