global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["98.71.55.191:9100"]
        labels:
          instance: node-exporter
  - job_name: "flask"
    static_configs:
      - targets: ["98.71.52.159:8000", "98.71.53.2:8000"]
        labels:
          instance: flask-exporter
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
        labels:
          instance: prometheus
  - job_name: nginx
    metrics_path: /prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["kristinadev.me:9113"]