global:
    scrape_interval: 5s

scrape_configs:
    - job_name: "node"
      static_configs:
          - targets: ["database.kristinadev.me:9100"]
            labels:
                instance: node-exporter
    - job_name: "flask"
      static_configs:
          - targets:
                [
                    "appserver1.kristinadev.me:8000",
                    "appserver2.kristinadev.me:8000",
                ]
            labels:
                instance: flask-exporter
    - job_name: "prometheus"
      static_configs:
          - targets: ["0.0.0.0:9090"]
            labels:
                instance: prometheus
    - job_name: nginx
      metrics_path: /prometheus
      scrape_interval: 30s
      static_configs:
          - targets: ["kristinadev.me:9113"]

alerting:
    alertmanagers:
        - static_configs:
              - targets:
                    - 74.234.102.17:9093
rule_files:
    - rules.yml
