groups:
- name: Total number of Get Requests
  rules:
  - alert: More than 15 requests
    expr: flask_http_request_total{method="GET",status="200"} > 15 and flask_http_request_total{method="GET",status="200"} < 50
    for: 5s
