name: Pytest

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:
    secrets:
      PROMETHEUS_MULTIPROC_DIR:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROMETHEUS_MULTIPROC_DIR: ${{ secrets.PROMETHEUS_MULTIPROC_DIR }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.13"

      - name: Set up a virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Check distutils
        run: python -c "import distutils.util"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up environment variable
        run: echo "PROMETHEUS_MULTIPROC_DIR=${PROMETHEUS_MULTIPROC_DIR}" >> $GITHUB_ENV

      - name: Running Tests
        run: |
          make test
